# Generated by Django 4.2.6 on 2025-08-01 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifications',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hotel.booking'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelgallery',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='Hotel.hotel'),
        ),
        migrations.AddField(
            model_name='hotelfeatures',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='Hotel.hotel'),
        ),
        migrations.AddField(
            model_name='hotelfaqs',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='Hotel.hotel'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestactivitylog',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.booking'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.hotel'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='Hotel.coupon'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hotel.hotel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ManyToManyField(to='Hotel.room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hotel.roomtype'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='roomtype',
            unique_together={('hotel', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hotel', 'room_number')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'hotel')},
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['user', 'seen'], name='Hotel_notif_user_id_8dd040_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hotelfeatures',
            unique_together={('hotel', 'name')},
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['status', 'featured'], name='Hotel_hotel_status_3051f8_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['city', 'status'], name='Hotel_hotel_city_b60df6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'hotel')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date', 'payment_status'], name='Hotel_booki_booking_be1ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['checkin_date', 'checkout_date'], name='Hotel_booki_checkin_2f0492_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'payment_status'], name='Hotel_booki_user_id_b6f1fb_idx'),
        ),
    ]
