# Generated by Django 4.2.6 on 2025-08-02 10:45

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='hotel', chained_model_field='hotel', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Hotel.roomtype'),
        ),
    ]
