# Generated by Django 4.2.6 on 2023-12-12 10:01

import Hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_booking_alter_hotel_description_staffonduty_roomtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=Hotel.models.Booking.generate_random_string, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='tags',
            field=models.CharField(blank=True, help_text='separate tags with comma', max_length=255, null=True),
        ),
    ]
