# Generated by Django 4.2.6 on 2024-03-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_LIJSNNS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
