# Generated by Django 4.2.6 on 2023-12-12 10:02

import Hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_booking_booking_id_alter_hotel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=Hotel.models.Booking.generate_random_string, max_length=10, unique=True),
        ),
    ]
