# Generated by Django 4.2.6 on 2024-03-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_booking_payment_lijsnns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_LIJSNNS',
        ),
    ]
