# Generated by Django 4.2.6 on 2023-12-18 18:40

import Hotel.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_alter_booking_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='hotel_gallery/roomType'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=Hotel.models.generate_random_string, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomtypes', to='Hotel.hotel'),
        ),
    ]
