# Generated by Django 4.2.6 on 2024-01-11 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_roomtype_image_alter_booking_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelgallery',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='Hotel.hotel'),
        ),
    ]
