# Generated by Django 4.2.6 on 2024-03-06 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0006_booking_date_of_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_of_booking',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 9, 48, 30, 530569)),
        ),
    ]
