# Generated by Django 4.2.6 on 2024-01-11 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0007_remove_hotel_tags_hotel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelfeatures',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_features', to='Hotel.hotel'),
        ),
    ]
