# Generated by Django 4.2.6 on 2024-03-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0007_alter_booking_date_of_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_of_booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
