# Generated by Django 4.2.6 on 2024-03-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0008_remove_booking_date_of_booking_booking_booking_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_availabe',
            new_name='is_active',
        ),
    ]
