# Generated by Django 4.2.6 on 2024-03-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0009_rename_is_availabe_booking_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='soon',
            new_name='seen',
        ),
    ]
