# Generated by Django 4.2.6 on 2024-03-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0010_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(default='Percentage', max_length=50),
        ),
    ]
