# Generated by Django 4.2.6 on 2024-03-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0010_rename_soon_notifications_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
