# Generated by Django 4.2.6 on 2024-03-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0011_alter_coupon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='Hotel.coupon'),
        ),
    ]
