# Generated by Django 4.2.6 on 2024-03-01 18:59

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0012_booking_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='success_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz', blank=True, length=10, max_length=10, null=True, prefix=''),
        ),
    ]
