"""
Django settings for travel_booking_platform project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y)nh8u!wv1uw=(x_i+c#ji&)#49-^3&de$jg)_m(9a2kdl30+c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [    
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # custom apps
    'Addon',
    'Hotel',
    'User_dashboard',
    'UserAuth',
    'booking',
    
    #third party libraries
    'crispy_forms',
    'bootstrap5',
    'fontawesomefree',
    'django_ckeditor_5',
    'ckeditor_uploader',
    'taggit',
    'import_export',
    'mathfilters',

    
] 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'travel_booking_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'travel_booking_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static',)]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# where jango will look for new user model
AUTH_USER_MODEL = "UserAuth.User"

# LOGIN_REDIRECT_URL ='account'
# LOGIN_URL='login'
# LOGOUT_URL ='logout'
# LOGOUT_REDIRECT_URL ='home'
# if DEBUG:
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# else:
#     # settings.py

#     EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#     EMAIL_HOST = 'your_smtp_server'
#     EMAIL_PORT = 587
#     EMAIL_USE_TLS = True
#     EMAIL_HOST_USER = 'your_email@example.com'
#     EMAIL_HOST_PASSWORD = 'your_email_password'

#     # settings.py

#     PASSWORD_RESET_SUBJECT = 'Password Reset'
#     PASSWORD_RESET_MESSAGE = 'Follow the link to reset your password: {link} \n your username is {username} incase you forgot \n\n\n if it was not you, please ignore this email'



JAZZMIN_SETTINGS ={
    'site_header': 'KALAHARI',
    'site_brand': 'Kalahari travel',
    #'site_logo':
    'copyright':"All rights reserved",
    'welcome_sign':'Welcome to KALAHARI travel administration',
    'topmenu_links':[
        {'name':'Home','url':"admin:index",'permissions':["auth.view_user"]},
        {'name':'Company','url':"/admin/addons/company/"},
        {'name':'Users','url':"/admin/userauths/user/"},
        {'model':'AUTH_USER_MODEL.User'},
        # {'name':'Home','url':"admin:index",'permissions':["auth.view_user"]},
    ],
    "oder_with_respect_to":[
        'hotel',
        'hotel.Hotel',
        'hotel.Room',
        'hotel.Booking',
        'hotel.BookingDetail',
        'hotel.Guest',
        'hotel.RoomServices',
        'userauths',
        'addons',
    ],

    'icons':{
        'admin.logEntry': "fas fa-file",

        'auth' : 'fas fa-user-cog',
        'auth.User': "fas fa-user",

        'userauths.User': "fas fa-user",
        'userauths.Profile': "fas fa-address-card",

        "hotel.Hotel": "fas fa-th",
        "hotel.Booking": "fas fa-calender-month",
        "hotel.BookingDetail": "fas fa-calender-alt",
        "hotel.Guest": "fas fa-user",
        "hotel.Room": "fas fa-bed",
        "hotel.RoomServices": "fas fa-user-cog",
        "hotel.Notification": "fas fa-bell",
        "hotel.Caupon": "fas fa-tag",
        "hotel.Bookmark": "fas fa-heart",

    },
    "show_ui_builder" : True,
}
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    'footer_small_text': False,
    "body_small_text": True,
    "brand_small_text": True,
    "brand_color":"navbar-indigo",
    "accent": "accent-olivegreen",
    "navbar" : "navbar-indigo navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar" : "sidebar-dark-indigo",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    #"theme":"default",
    #"dark_mode_theme": "None",
    "button_classes" : {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success" : "btn-success",
    }
}
customColorPalete =[
    {"color": "hsl(4,90%,58%)", "label": "Red",},
    {"color": "hsl(340,82%,52%)", "label": "pink",},
    {"color": "hsl(291,64%,42%)", "label": "Purple",},
    {"color": "hsl(262,52%,47%)", "label": "Deep Purple",},
    {"color": "hsl(321,48%,48%)", "label": "Indigo",},
    {"color": "hsl(207,90%,54%)", "label": "Blue",},
]
CKEDITOR_5_CONFIGS= {
    "default": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "link",
            "bulletedList",
            "numberedList",
            "blockQuote",
            "imageUpload",
        ],
    },
    "comment": {
        "language":{"ui": "en","content": "en"},
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "bulletedList",
            "numberedList",
            "blockQuote",
        ],
    },
    "extends": {
        "language": "en",
        "enterMode": 2,
        "shiftEnterMode": 1,
        "blockToolbar":[
            "paragraph",
            "heading1",
            "heading2",
            "heading3",
            "heading4",
            "|",
            "bulletedList",
            "numberedList",
            "|",
            "blockQuote",
        ],
        "toolbar":[
            "heading",
            "|",
            "|",
            "bold",
            "italic",
            "link",
            "underline",
            "strikethrough",
            "code",
            "subscript",
            "superscript",
            "highlight",
            "|",
            "bulletedList",
            "codeBlock",
            "numberedList",
            "todoList",
            "|",
            "outdent",
            "indent",
            "|",
            "blockQuote",
            "insertImage",
            "|",
            "fontSize",
            "fontFamily",
            "fontColor",
            "fontBackgroundColor",
            "mediaEmbed",
            "removeFormat",
            "insertTable",
            "sourceEditing",
            "|",

        ],
        "images": {
            "toolbar": [
                "imageTextAlternative",
                "|",
                "imageStyle:alignLeft",
                "imageStyle:alignRight",
                "imageStyle:alignCenter",
                "imageStyle:side",
                "|",
                "toggleImageCaption",
                "|",
            ],
        },
        "table":{
            "contentToolbar": [
                "tableColumn",
                "tableRow",
                "mereTableCells",
                "tableProperties",
                "tableCellProperties",
            ],
            "tableProperties":{
                "borderColors": customColorPalete,
                "backgroundColors": customColorPalete,

            },
            "tableCellProperties":{
                "borderColors": customColorPalete,
                "backgroundColors": customColorPalete,  
            },
        },
        "heading":{
            "options":[
                {
                    "model":"paragraph",
                    "title":"paragraph",
                    "class":"ck-heading_paragraph",
                },
                {
                    "model":"heading1",
                    "view":"h1",
                    "title":"Heading 1",
                    "class":"ck-heading_heading1",
                },
                {
                    "model":"heading2",
                    "view":"h1",
                    "title":"Heading 2",
                    "class":"ck-heading_heading2",
                },
                {
                    "model":"heading3",
                    "view":"h1",
                    "title":"Heading 3",
                    "class":"ck-heading_heading3",
                },
            ],
        },
        "list":{
            "properties":{
                "style": True,
                "startIndex": True,
                "reversed": True,
            }
        },
        "htmlSupport": {
            "allow":[
                {'name':"/.*/","attributes":True, "classes":True,"styles":True}
            ],
        }
    },

}